# Generated by Django 3.2 on 2022-02-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='region')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('gps', models.CharField(blank=True, max_length=50, null=True, verbose_name='gps')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('tip', models.CharField(blank=True, choices=[('MEDIUM_VOLTAGE', 'MEDIUM_VOLTAGE'), ('LOW_VOLTAGE', 'LOW_VOLTAGE'), ('HIGH_VOLTAGE', 'HIGH_VOLTAGE')], max_length=50, null=True, verbose_name='tip')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='brand')),
                ('model_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='model_name')),
                ('serial_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='serial_no')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('voltage', models.IntegerField(verbose_name='voltage')),
                ('is_live', models.BooleanField(default=True, verbose_name='is live ?')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.area', verbose_name='area')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='ComServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('ip1', models.CharField(default='192.168.1.254', max_length=50, verbose_name='ip1')),
                ('port1', models.CharField(default='502', max_length=50, verbose_name='port1')),
                ('ip2', models.CharField(default='192.168.2.254', max_length=50, verbose_name='ip2')),
                ('port2', models.CharField(default='8080', max_length=50, verbose_name='port2')),
                ('username', models.CharField(default='root', max_length=50, verbose_name='username')),
                ('password', models.CharField(default='root', max_length=50, verbose_name='password')),
                ('redundancy', models.CharField(choices=[('HOT', 'HOT'), ('STAND_BY', 'STAND_BY')], default='HOT', max_length=50, verbose_name='redundancy')),
                ('interval', models.IntegerField(default=5000, verbose_name='interval')),
            ],
            options={
                'verbose_name': 'ComServer',
                'verbose_name_plural': 'ComServers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('current_transformers_ratio', models.IntegerField(default=60, verbose_name='feeder_current_transformers_ratio')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('voltage_transformers_ratio', models.IntegerField(default=350, verbose_name='feeder_voltage_transformers_ratio')),
                ('register_cb_open', models.IntegerField(default=3, verbose_name='register_cb_open')),
                ('register_cb_close', models.IntegerField(default=4, verbose_name='register_cb_close')),
                ('register_cb_test', models.IntegerField(default=1, verbose_name='register_cb_test')),
                ('register_cb_trip', models.IntegerField(default=2, verbose_name='register_cb_trip')),
                ('register_cb_servive', models.IntegerField(default=28, verbose_name='register_cb_servive')),
                ('register_cb_spare1', models.IntegerField(default=5, verbose_name='register_cb_spare1')),
                ('register_cb_spare2', models.IntegerField(default=6, verbose_name='register_cb_spare2')),
                ('register_ct_i_a', models.IntegerField(default=7, verbose_name='register I a')),
                ('register_ct_i_b', models.IntegerField(default=8, verbose_name='register I b')),
                ('register_ct_i_c', models.IntegerField(default=9, verbose_name='register I c')),
                ('register_vt_v_a', models.IntegerField(default=10, verbose_name='register V a')),
                ('register_vt_v_b', models.IntegerField(default=11, verbose_name='register V b')),
                ('register_vt_v_c', models.IntegerField(default=12, verbose_name='register V c')),
                ('register_vt_v_ab', models.IntegerField(default=13, verbose_name='register V ab')),
                ('register_vt_v_bc', models.IntegerField(default=14, verbose_name='register V bc')),
                ('register_vt_v_ac', models.IntegerField(default=15, verbose_name='register V ac')),
                ('register_q', models.IntegerField(default=16, verbose_name='register q')),
                ('register_p', models.IntegerField(default=17, verbose_name='register p')),
                ('register_s', models.IntegerField(default=18, verbose_name='register s')),
                ('circuit_breaker_status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('TESTING', 'TESTING'), ('FAILED', 'FAILED')], default='TESTING', max_length=50, verbose_name='circuit_breaker_status')),
                ('i_a', models.IntegerField(blank=True, null=True, verbose_name='I a')),
                ('i_b', models.IntegerField(blank=True, null=True, verbose_name='I b')),
                ('i_c', models.IntegerField(blank=True, null=True, verbose_name='I c')),
                ('v_a', models.IntegerField(blank=True, null=True, verbose_name='V a')),
                ('v_b', models.IntegerField(blank=True, null=True, verbose_name='V b')),
                ('v_c', models.IntegerField(blank=True, null=True, verbose_name='V c')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.bus', verbose_name='bus')),
                ('com_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.comserver', verbose_name='com_server')),
            ],
            options={
                'verbose_name': 'Feeder',
                'verbose_name_plural': 'Feeders',
            },
        ),
        migrations.CreateModel(
            name='FeederComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('origin_value', models.IntegerField(verbose_name='origin_value')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.feeder', verbose_name='feeder')),
            ],
            options={
                'verbose_name': 'FeederComponent',
                'verbose_name_plural': 'FeederComponents',
            },
        ),
        migrations.CreateModel(
            name='CurrentTransformer',
            fields=[
                ('feedercomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web2.feedercomponent')),
            ],
            options={
                'verbose_name': 'CurrentTransformerData',
                'verbose_name_plural': 'CurrentTransformerDatas',
            },
            bases=('web2.feedercomponent',),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.IntegerField(verbose_name='register')),
                ('can_read', models.BooleanField(default=False, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('com_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.comserver', verbose_name='comserver')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web2.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('register', models.IntegerField(default=0, verbose_name='register')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('status', models.CharField(choices=[('ENABLE', 'ENABLE'), ('DISABLE', 'DISABLE'), ('TOGGLE', 'TOGGLE'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('POWER_ON', 'POWER_ON'), ('POWER_OFF', 'POWER_OFF'), ('START', 'START'), ('STOP', 'STOP'), ('INSTALLED', 'INSTALLED'), ('REMOVED', 'REMOVED'), ('unable to connect !', 'unable to connect !')], max_length=50, verbose_name='status')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('com_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web2.comserver', verbose_name='com_server')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web2.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='ComServerDataBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.IntegerField(default=1, verbose_name='start_address')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('code_name', models.CharField(choices=[('READ_COILS', 'READ_COILS'), ('WRITE_SINGEL_COIL', 'WRITE_SINGEL_COIL'), ('READ_HOLDING_REGISTERS', 'READ_HOLDING_REGISTERS')], max_length=50, verbose_name='code')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('com_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.comserver', verbose_name='comserver')),
            ],
            options={
                'verbose_name': 'ComServerDataBlock',
                'verbose_name_plural': 'ComServerDataBlocks',
            },
        ),
    ]
