# Generated by Django 3.2 on 2022-02-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogComponent',
            fields=[
                ('feedercomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web2.feedercomponent')),
            ],
            options={
                'verbose_name': 'AnalogComponent',
                'verbose_name_plural': 'AnalogComponents',
            },
            bases=('web2.feedercomponent',),
        ),
        migrations.CreateModel(
            name='BinaryComponent',
            fields=[
                ('feedercomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web2.feedercomponent')),
            ],
            options={
                'verbose_name': 'BinaryComponent',
                'verbose_name_plural': 'BinaryComponent',
            },
            bases=('web2.feedercomponent',),
        ),
        migrations.DeleteModel(
            name='CurrentTransformer',
        ),
    ]
