# Generated by Django 4.0.3 on 2022-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0004_feeder_p_feeder_power_factor_feeder_q_feeder_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedercomponent',
            name='register',
            field=models.IntegerField(default=0, verbose_name='register'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_close',
            field=models.IntegerField(default=0, verbose_name='register_cb_close'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_open',
            field=models.IntegerField(default=0, verbose_name='register_cb_open'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_servive',
            field=models.IntegerField(default=0, verbose_name='register_cb_servive'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_spare1',
            field=models.IntegerField(default=0, verbose_name='register_cb_spare1'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_spare2',
            field=models.IntegerField(default=0, verbose_name='register_cb_spare2'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_test',
            field=models.IntegerField(default=0, verbose_name='register_cb_test'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_trip',
            field=models.IntegerField(default=0, verbose_name='register_cb_trip'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_ct_i_a',
            field=models.IntegerField(default=0, verbose_name='register I a'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_ct_i_b',
            field=models.IntegerField(default=0, verbose_name='register I b'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_ct_i_c',
            field=models.IntegerField(default=0, verbose_name='register I c'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_p',
            field=models.IntegerField(default=0, verbose_name='register p'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_power_factor',
            field=models.IntegerField(default=0, verbose_name='register_power_factor'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_q',
            field=models.IntegerField(default=0, verbose_name='register q'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_s',
            field=models.IntegerField(default=0, verbose_name='register s'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_vt_v_a',
            field=models.IntegerField(default=0, verbose_name='register V a'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_vt_v_ab',
            field=models.IntegerField(default=0, verbose_name='register V ab'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_vt_v_ac',
            field=models.IntegerField(default=0, verbose_name='register V ac'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_vt_v_b',
            field=models.IntegerField(default=0, verbose_name='register V b'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_vt_v_bc',
            field=models.IntegerField(default=0, verbose_name='register V bc'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_vt_v_c',
            field=models.IntegerField(default=0, verbose_name='register V c'),
        ),
    ]
