# Generated by Django 4.0.3 on 2022-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0005_feedercomponent_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='brand',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='model_name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='model_name'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='serial_no',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='serial_no'),
        ),
        migrations.AlterField(
            model_name='comserver',
            name='ip1',
            field=models.CharField(default='192.168.1.24', max_length=50, verbose_name='ip1'),
        ),
        migrations.AlterField(
            model_name='comserver',
            name='port1',
            field=models.CharField(default='504', max_length=50, verbose_name='port1'),
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='description'),
        ),
    ]
