# Generated by Django 4.1 on 2022-08-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0006_alter_bus_brand_alter_bus_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeder',
            old_name='register_cb_servive',
            new_name='register_cb_service',
        ),
    ]
