# Generated by Django 4.0.3 on 2022-06-08 00:29

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
            bases=(models.Model, core.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ComServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ComServer',
                'verbose_name_plural': 'ComServers',
            },
            bases=(models.Model, core.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bus', verbose_name='bus')),
                ('com_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.comserver', verbose_name='com_server')),
            ],
            options={
                'verbose_name': 'Feeder',
                'verbose_name_plural': 'Feeders',
            },
            bases=(models.Model, core.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ComServerDataBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('com_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.comserver', verbose_name='com_server')),
            ],
            options={
                'verbose_name': 'ComServerDataBlock',
                'verbose_name_plural': 'ComServerDataBlock',
            },
            bases=(models.Model, core.models.LinkHelper),
        ),
    ]
