# Generated by Django 3.2 on 2021-11-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='register_cb_servive',
            field=models.IntegerField(default=28, verbose_name='register_cb_trip'),
        ),
    ]
