# Generated by Django 4.0.3 on 2022-08-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comserver',
            name='interval',
            field=models.IntegerField(default=5000, verbose_name='interval'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='ip1',
            field=models.CharField(default='192.168.1.24', max_length=50, verbose_name='ip1'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='ip2',
            field=models.CharField(default='192.168.2.254', max_length=50, verbose_name='ip2'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='password',
            field=models.CharField(default='root', max_length=50, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='port1',
            field=models.CharField(default='504', max_length=50, verbose_name='port1'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='port2',
            field=models.CharField(default='8080', max_length=50, verbose_name='port2'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='redundancy',
            field=models.CharField(choices=[('HOT', 'HOT'), ('STAND_BY', 'STAND_BY')], default='HOT', max_length=50, verbose_name='redundancy'),
        ),
        migrations.AddField(
            model_name='comserver',
            name='username',
            field=models.CharField(default='root', max_length=50, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='comserverdatablock',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comserverdatablock',
            name='start',
            field=models.IntegerField(default=1, verbose_name='start'),
            preserve_default=False,
        ),
    ]
