# Generated by Django 3.2 on 2021-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_feeder_register_cb_servive'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='circuit_breaker_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('TESTING', 'TESTING'), ('FAILED', 'FAILED')], default='jgghfg', max_length=50, verbose_name='circuit_breaker_status'),
            preserve_default=False,
        ),
    ]
