# Generated by Django 3.2 on 2021-11-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_feeder_circuit_breaker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutput',
            name='status',
            field=models.CharField(choices=[('DISCONNECTED', 'DISCONNECTED'), ('SUCCESSFULL', 'SUCCESSFULL'), ('FAILED', 'FAILED'), ('INVALID', 'INVALID')], default='DISCONNECTED', max_length=50, verbose_name='status'),
        ),
    ]
