# Generated by Django 3.2 on 2021-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_inputoutput_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analoginput',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='value'),
        ),
    ]
