# Generated by Django 3.2 on 2021-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_analoginput_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='i_a',
            field=models.IntegerField(default=1, verbose_name='i_a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeder',
            name='i_b',
            field=models.IntegerField(default=1, verbose_name='i_b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeder',
            name='i_c',
            field=models.IntegerField(default=1, verbose_name='i_c'),
            preserve_default=False,
        ),
    ]
