# Generated by Django 3.2 on 2021-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20211114_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analoginput',
            name='value',
        ),
        migrations.RemoveField(
            model_name='binaryinput',
            name='value',
        ),
        migrations.AddField(
            model_name='inputoutput',
            name='origin_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='origin_value'),
        ),
    ]
