# Generated by Django 3.2 on 2021-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20211114_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='i_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='i_a'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='i_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='i_b'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='i_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='i_c'),
        ),
    ]
