# Generated by Django 3.2 on 2021-11-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20211114_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='voltage',
            field=models.IntegerField(default=220, verbose_name='voltage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeder',
            name='circuit_breaker_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('TESTING', 'TESTING'), ('FAILED', 'FAILED')], default='TESTING', max_length=50, verbose_name='circuit_breaker_status'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='i_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='I a'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='i_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='I b'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='i_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='I c'),
        ),
        migrations.CreateModel(
            name='CurrentTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.feeder', verbose_name='feeder')),
            ],
            options={
                'verbose_name': 'CurrentTransformer',
                'verbose_name_plural': 'CurrentTransformers',
            },
        ),
    ]
