# Generated by Django 3.2 on 2022-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_feeder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='current_transformers_ratio',
            field=models.IntegerField(default=60, verbose_name='feeder_current_transformers_ratio'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='v_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='V a'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='v_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='V b'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='v_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='V c'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='voltage_transformers_ratio',
            field=models.IntegerField(default=350, verbose_name='feeder_voltage_transformers_ratio'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='register_cb_servive',
            field=models.IntegerField(default=28, verbose_name='register_cb_servive'),
        ),
    ]
